import { CateringStation } from '@/types/catering';

export const OFFICIAL_IRCTC_URL = 'https://www.ecatering.irctc.co.in/';

export interface StationCateringConfig {
  stationCode: string;
  stationName: string;
  available: boolean;
  serviceType: 'ecatering' | 'meal' | 'restaurant';
  provider: 'IRCTC_ECATERING';
  orderingUrl: string;
  specialties: string[];
  cutoffMinutes: number;
}

export const STATION_CATERING_DATASET: Record<string, StationCateringConfig> = {
  ST: {
    stationCode: 'ST',
    stationName: 'Surat',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Fresh Surat Khaman', 'Surati Locho', 'Ghari Sweets'],
    cutoffMinutes: 30,
  },
  CNB: {
    stationCode: 'CNB',
    stationName: 'Kanpur Central',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Kulhad Masala Chai', 'Kanpur Samosa', 'Chana Puri'],
    cutoffMinutes: 35,
  },
  KOTA: {
    stationCode: 'KOTA',
    stationName: 'Kota Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Rajasthani Dal Baati Churma', 'Pyaaz Kachori', 'Kota Samosa'],
    cutoffMinutes: 30,
  },
  NDLS: {
    stationCode: 'NDLS',
    stationName: 'New Delhi',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Deluxe North Indian Thali', 'Chole Bhature', 'Biryani Combo'],
    cutoffMinutes: 40,
  },
  MMCT: {
    stationCode: 'MMCT',
    stationName: 'Mumbai Central',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Mumbai Vada Pav', 'Pav Bhaji', 'Maharashtrian Thali'],
    cutoffMinutes: 35,
  },
  CSMT: {
    stationCode: 'CSMT',
    stationName: 'Mumbai CST',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Bombay Sandwich', 'Keema Pav', 'Cutting Chai'],
    cutoffMinutes: 35,
  },
  HWH: {
    stationCode: 'HWH',
    stationName: 'Howrah Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Kolkata Chicken Biryani', 'Macha Jhol Thali', 'Rosogolla'],
    cutoffMinutes: 40,
  },
  SDAH: {
    stationCode: 'SDAH',
    stationName: 'Sealdah',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Bengali Fish Curry', 'Kolkata Kathi Rolls', 'Mishti Doi'],
    cutoffMinutes: 35,
  },
  MAS: {
    stationCode: 'MAS',
    stationName: 'Chennai Central',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['South Indian Meals', 'Ghee Masala Dosa', 'Filter Coffee'],
    cutoffMinutes: 30,
  },
  BSB: {
    stationCode: 'BSB',
    stationName: 'Varanasi Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Banarasi Malaiyo', 'Kashi Rabri Jalebi', 'Poori Sabzi'],
    cutoffMinutes: 35,
  },
  SBC: {
    stationCode: 'SBC',
    stationName: 'KSR Bengaluru',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Bisi Bele Bath', 'Rava Idli', 'Mysore Pak'],
    cutoffMinutes: 30,
  },
  ADI: {
    stationCode: 'ADI',
    stationName: 'Ahmedabad Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Gujarati Jain Thali', 'Dhokla & Fafda', 'Khandvi'],
    cutoffMinutes: 35,
  },
  BPL: {
    stationCode: 'BPL',
    stationName: 'Bhopal Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Bhopali Poha Jalebi', 'Mughlai Biryani', 'Samosa Chat'],
    cutoffMinutes: 30,
  },
  LKO: {
    stationCode: 'LKO',
    stationName: 'Lucknow Charbagh',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Lucknawi Veg Biryani', 'Basket Chaat', 'Awadhi Meals'],
    cutoffMinutes: 35,
  },
  PNBE: {
    stationCode: 'PNBE',
    stationName: 'Patna Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Bihari Litti Chokha', 'Sattu Paratha', 'Anarsa Sweets'],
    cutoffMinutes: 35,
  },
  PUNE: {
    stationCode: 'PUNE',
    stationName: 'Pune Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Puneri Misal Pav', 'Bhakarwadi', 'Puran Poli'],
    cutoffMinutes: 30,
  },
  NGP: {
    stationCode: 'NGP',
    stationName: 'Nagpur Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Nagpuri Tarri Poha', 'Orange Barfi', 'Saoji Veg Thali'],
    cutoffMinutes: 30,
  },
  BZA: {
    stationCode: 'BZA',
    stationName: 'Vijayawada Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Andhra Spicy Thali', 'Hyderabadi Dum Biryani', 'Punugulu'],
    cutoffMinutes: 35,
  },
  BRC: {
    stationCode: 'BRC',
    stationName: 'Vadodara Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Sev Usal', 'Gujarati Kathiyawadi Thali', 'Dal Wada'],
    cutoffMinutes: 30,
  },
  RTM: {
    stationCode: 'RTM',
    stationName: 'Ratlam Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Ratlami Sev Mixture', 'Malwa Poha', 'Garadu Snack'],
    cutoffMinutes: 25,
  },
  NZM: {
    stationCode: 'NZM',
    stationName: 'Hazrat Nizamuddin',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Mughlai Rolls', 'Butter Chicken Thali', 'Paneer Tikka Meal'],
    cutoffMinutes: 35,
  },
  PRYJ: {
    stationCode: 'PRYJ',
    stationName: 'Prayagraj Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Dehati Jalebi', 'Kachori Sabzi', 'Allahabadi Gujiya'],
    cutoffMinutes: 30,
  },
  GKP: {
    stationCode: 'GKP',
    stationName: 'Gorakhpur Junction',
    available: true,
    serviceType: 'ecatering',
    provider: 'IRCTC_ECATERING',
    orderingUrl: OFFICIAL_IRCTC_URL,
    specialties: ['Purvanchal Thali', 'Samosa Khas', 'Pedas'],
    cutoffMinutes: 30,
  },
};

/**
 * Gets station catering config by station code.
 */
export function getStationCateringConfig(code: string): StationCateringConfig | null {
  const upper = (code || '').toUpperCase().trim();
  return STATION_CATERING_DATASET[upper] || null;
}
